Repository Anneryshc/is373_devops_hexo, pull requests merged in 2024-10, with the labels that each got.

#4 fix 6
  .github/workflows/hexo.yml
  _config.yml
Labels: bug, documentation

#5 Update hexo.yml to fix jekyl fix2
  .github/workflows/hexo.yml
Labels: bug

#6 Trying to fix jekyll deployment error
  .github/workflows/hexo.yml
  _config.yml
Labels: duplicate

#7 Update hexo.yml jekyl problem
  .github/workflows/hexo.yml
Labels: bug

#8 Update hexo.yml jekyl problem again
  .github/workflows/hexo.yml
Labels: bug

#9 Update hexo.yml jekyll fix again
  .github/workflows/hexo.yml
Labels: bug
